"""
Usage:
    # local
    uv run just local-run

    # SLURM
    uv run just slurm-run

    # dry run
    uv run just dry-run
"""

# shared config
include: "rules/common.smk"

# include rule files
if STAGES.get('generate_negatives', False):
    include: "rules/generate_negative_dhs.smk"
if STAGES.get('prepare_dhs', True):
    include: "rules/prepare_dhs.smk"
if STAGES.get('collect_data', True):
    include: "rules/preprocessing.smk"
if STAGES.get('train', True):
    include: "rules/training.smk"
if STAGES.get('inference', True):
    include: "rules/inference.smk"
if STAGES.get("accessibility_scores", False):
    include: "rules/accessibility_scores.smk"
if STAGES.get("benchmark", False):
    include: "rules/benchmark.smk"


# build final targets
TARGETS = []

if STAGES.get("generate_negatives", False):
    TARGETS.append(f"{TRAIN_DHS_DIR}.negatives_done")

if STAGES.get('prepare_dhs', True):
    TARGETS += expand(
        f"{TRAIN_DHS_DIR}{{dhs_file}}_wl{MATRIX_COLUMNS}.bed",
        dhs_file=DHS_FILES,
    )

# training
if STAGES.get('train', True):
    TARGETS.append(MODEL["checkpoint"])

# inference
if STAGES.get('inference', True):
    TARGETS += expand(
        f"{ACCESSIBILITY_DIR}{{sample}}__{{dhs_file}}.cov.txt",
        sample=INFERENCE_SAMPLES, dhs_file=INFERENCE_DHS_FILES,
    )

if STAGES.get("benchmark", False):
    TARGETS += expand(
        f"{FINAL_MATRICES_DIR}feature_matrix_{{stat}}.parquet",
        stat=BENCH_STATS,
    )

rule all:
    input: TARGETS
