executor: slurm
jobs: 20
cores: 10
use-conda: true
default-resources:
  slurm_account: Fragmentomics
  runtime: 30
  mem_mb: 500
  disk_mb: 1000
group-components:
  prep_dhs: 50
  downsample_dhs: 50
  prep_frag: 50
  downsample_matrices: 50
  rebin_matrices: 50
  inference: 50
  pfe: 50
  ocf: 50
  ifs: 50
  fdi: 50
  lwps: 50
