executor: slurm
jobs: 20
use-conda: true
default-resources:
  slurm_account: Fragmentomics
  runtime: 30
  mem_mb: 500
group-components:
  sort_dhs: 50
  prep_dhs: 50
  downsample_dhs: 50
  sort_frag: 50
  prep_frag: 50
  downsample_matrices: 50
  rebin_matrices: 50
  inference: 50
