# cfDNA Project Configuration
env_name: "cfDNA_project"


# common
input_frags_dir: "../raw_data/cristiano_healthy/"  # needs to be created
hg_38_2bit_file: "../raw_data/hg38.2bit"  # needs to be created
sorted_frags_dir: "../raw_data/cristiano_healthy_sorted/"
matrix_columns: 2500
matrix_shift: 250
matrix_rows: 300
dhs_gc_bias_window: 200
n_rebin_rows: 50


# training
training_dhs_dir: "../raw_data/training_dhs/"  # needs to be created
training_output_dir: "../data/training_frags/"  # needs to be created
training_sorted_dhs_dir: "../raw_data/training_dhs_sorted/"
training_min_coverage_file: "../data/training_frags/min_coverage.txt"
training_bin_edges_file: "../data/training_frags/bin_edges.npy"

train_size: 80
valid_size: 10
batch_size: 32


# inference
inference_dhs_dir: "../raw_data/inference_dhs/"  # needs to be created
inference_frags_dir: "../raw_data/cristiano_cfdnas/"  # needs to be created
inference_sorted_frags_dir: "../data/inference_sorted_frags/"
inference_output_dir: "../data/inference/"
inference_sorted_dhs_dir: "../raw_data/inference_dhs_sorted/"

model_checkpoint: "./models/cnn_rebinned_46x2000.pt"  # needs to be created
inference_model_type: "cnn_model"  # either cnn_model or mlp_model for now
inference_use_rebinned: true


# benchmark
accessibility_scores_dir: "../data/cristiano_cfdnas_dhs/"  # needs to be created from @project_scripts
final_matrices_dir: "../data/final_matrices/"
metadata_path: "../raw_data/cristiano_cfdnas/meta_data.csv"
paper: "Genome-wide cell-free DNA fragmentation in patients with cancer"